### ISSUE TITLE
Download gettext files

### ISSUE THREAD

**Issue by helgatheviking** [erasys/grunt-transifex#2]
Instead of json strings, would it be possible to download .po files? The transifex twitter account suggested that if the original file format is .po (Gettext), you can download .po files. That would be a big help for anyone using gettext.

**Comment by lwille** [comment]
Hi @helgatheviking, we'd be happy to accept a pull request for this feature. 
Unfortunately, we discontinued Transifex in our project, so we're not actively pushing development.

Maybe @transifex is interested in helping to maintain it?

**Comment by helgatheviking** [comment]
I understand. I'm not sure my nodeJS level is advanced enough for that, but if I get a change I will try. I asked @transifex for some documentation on the subject because I can't seem to find any. Hope they will pick up the gauntlet as grunt for transifex is a pretty awesome idea.
